# Riptide Clippy Configuration
# Enforces our documented coding standards

# Complexity limits
cognitive-complexity-threshold = 20
too-many-lines-threshold = 400
too-many-arguments-threshold = 5

# ENFORCE: No wildcard imports to prevent use module::*;
warn-on-all-wildcard-imports = true