# Riptide Clippy Configuration
# Enforces documented coding standards from docs/STYLE.md

# === SIZE LIMITS ===
# From STYLE.md: Functions 70 lines max, Modules 500 lines max
too-many-lines-threshold = 500
cognitive-complexity-threshold = 20
too-many-arguments-threshold = 6

# === NAMING AND STYLE ===
# Enforce idiomatic Rust patterns
enum-variant-name-threshold = 3
max-struct-bools = 3
warn-on-all-wildcard-imports = true

# === PERFORMANCE ===
# Prevent common performance issues
trivial-copy-size-limit = 64
pass-by-value-size-limit = 256

# === SAFETY ===
# These are handled by lib.rs #![deny(...)] directives:
# - missing_docs
# - missing_errors_doc
# - missing_panics_doc
# - unwrap_used
# - expect_used
# - panic

# === ERROR HANDLING ===
# Encourage proper error handling
# question-mark and result-unit-err don't exist as config options

# === COMPLEXITY ===
# Keep code simple and maintainable
type-complexity-threshold = 150
excessive-nesting-threshold = 7
