[toolchain]
# Rust toolchain specification for consistent local/CI builds
# Update this when upgrading Rust versions
channel = "nightly-2025-06-26"
components = ["rustfmt", "clippy", "rust-src"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "x86_64-pc-windows-msvc"]