name: CI

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-06-26
          components: rustfmt, clippy

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev libavdevice-dev libswscale-dev libswresample-dev

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Run clippy
        run: cargo clippy --workspace -- -D warnings

      - name: Test workspace
        run: cargo test --workspace

      - name: Build release
        run: cargo build --workspace --release

  build-matrix:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly-2025-06-26

      - name: Install FFmpeg (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg libavutil-dev libavformat-dev libavcodec-dev libavfilter-dev libavdevice-dev libswscale-dev libswresample-dev

      - name: Install FFmpeg (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install ffmpeg

      - name: Install FFmpeg (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          # Install vcpkg and ffmpeg for ffmpeg-sys-next compatibility
          git clone https://github.com/Microsoft/vcpkg.git C:\vcpkg
          C:\vcpkg\bootstrap-vcpkg.bat
          C:\vcpkg\vcpkg.exe install ffmpeg:x64-windows-static-md
          # Set environment variables for ffmpeg-sys-next
          echo "VCPKG_ROOT=C:\vcpkg" >> $env:GITHUB_ENV
          echo "FFMPEG_DIR=C:\vcpkg\installed\x64-windows-static-md" >> $env:GITHUB_ENV
          echo "FFMPEG_STATIC=1" >> $env:GITHUB_ENV
          echo "FFMPEG_PKG_CONFIG=0" >> $env:GITHUB_ENV

      - name: Build
        run: cargo build --workspace --release
